language: node_js
node_js:
  - lts/*

deploy:
  - provider: npm
    email: dineug2@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    local_dir: docs
    on:
      branch: master

script:
  - npm run test
  - npm run build
  - npm run storybook:build
